name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run docker compose down
        run: docker-compose down

      - name: Build and Start Docker Compose
        run: docker compose up --build -d
