name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Fix permissions
        run: sudo chown -R $USER:$USER /home/runner/actions-runner/_work/tochkaUrfu/tochkaUrfu

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run docker compose down
        run: docker compose down

      - name: Build and Start Docker Compose
        run: docker compose up --build -d
